version: 2

sources:
  - name: raw_data
    database: finance_db
    schema: raw
    tables:
     - name: customers   
       identifier: raw_customers  
     - name: orders
       identifier: raw_orders
     - name: order_items
       identifier: raw_order_items
     - name: products
       identifier: raw_products